//! Build-time workaround for an `apple-cryptokit-rs` + Xcode 26.x link failure.
//!
//! `apple-cryptokit-rs` builds its Swift sources with a low deployment target
//! (macOS 11 / iOS 13). At that target the Swift compiler bakes strong autolink
//! "force load" references to the back-deployment runtime shims
//! `swiftCompatibility56` and `swiftCompatibilityConcurrency` into its objects.
//! SwiftPM ignores `MACOSX_DEPLOYMENT_TARGET` and the target triple the
//! dependency passes, so the references can't be suppressed from the outside.
//!
//! Xcode 26.x removed those `libswiftCompatibility*.a` archives from the
//! toolchain, so linking fails with undefined
//! `__swift_FORCE_LOAD_$_swiftCompatibility56` / `...Concurrency` symbols.
//!
//! Those shims only patch Swift runtime bugs on macOS < 12.3 / iOS < 15, well
//! below what the CryptoKit APIs used here require, so they are no-ops on every
//! supported OS. We satisfy the references with empty marker symbols. When the
//! real archives are still present (older Xcode) the markers resolve the
//! references first, so the archives are never pulled in and there is no
//! duplicate-symbol conflict.
//!
//! # The real fix, and why it isn't done here
//!
//! The proper fix belongs in `apple-cryptokit-rs`: raise its
//! `swift/Package.swift` `platforms` from `.macOS(.v10_15)` to `.macOS(.v13)`
//! or higher. SwiftPM derives the Swift deployment target only from that
//! manifest; the `--triple` and `MACOSX_DEPLOYMENT_TARGET` the dependency's
//! build script sets affect only its own Rust codegen, not the Swift compile.
//! Rebuilding its Swift package confirms the threshold:
//!
//! | `platforms`       | back-deployment force-loads emitted            |
//! |-------------------|------------------------------------------------|
//! | `.macOS(.v10_15)` | both (today's break)                           |
//! | `.macOS(.v12)`    | `swiftCompatibility56` only (it needs >= 12.3) |
//! | `.macOS(.v13)`+   | none                                           |
//!
//! That bump is cheap in practice: macOS 13 (2022) and 14 (2023) are already
//! past Apple's security-update window, and the CryptoKit APIs wrapped here
//! need a recent OS anyway, so it drops no version Apple still services.
//!
//! We keep the stub instead because 0.2.1 is the latest published release and
//! carries no such fix. Going upstream today would mean a `[patch.crates-io]`
//! fork (a git pin plus ongoing maintenance) in place of a plain crates.io
//! dependency. The stub is self-contained, fork-free, and works on every Xcode
//! whether or not the shim archives ship. Once upstream raises its floor,
//! delete this file and the `cc` build-dependency in Cargo.toml.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();

    // Only Apple targets that actually compile and link the Swift `cryptokit`
    // static library are affected.
    if target_os != "macos" && target_os != "ios" {
        return;
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let stub = out_dir.join("swift_compat_force_load_stub.c");

    let stub_src = concat!(
        "/* Generated by build.rs: empty markers for Swift back-deployment\n",
        "   compatibility shims removed in Xcode 26.x. See build.rs. */\n",
        "char _swift_FORCE_LOAD_$_swiftCompatibility56 = 0;\n",
        "char _swift_FORCE_LOAD_$_swiftCompatibilityConcurrency = 0;\n",
    );
    fs::write(&stub, stub_src).expect("failed to write Swift compatibility stub source");

    cc::Build::new()
        .file(&stub)
        .flag_if_supported("-Wno-dollar-in-identifier-extension")
        .compile("str0m_swift_compat_stub");
}
